const DB_NAME = 'novel-audio-miner-dictionaries';
const DB_VERSION = 3;
const LEGACY_STORE_NAME = 'dictionarySnapshots';
const META_STORE_NAME = 'dictionaryMetas';
const ENTRY_STORE_NAME = 'dictionaryEntries';
const ACTIVE_KEY = 'active';
const TERM_ENTRY_CHUNK_SIZE = 5000;
function openDictionaryDatabase(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){reject(new Error('IndexedDB is not available in this browser.'));return;}const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(LEGACY_STORE_NAME))db.createObjectStore(LEGACY_STORE_NAME,{keyPath:'id'});if(!db.objectStoreNames.contains(META_STORE_NAME))db.createObjectStore(META_STORE_NAME,{keyPath:'id'});if(!db.objectStoreNames.contains(ENTRY_STORE_NAME))db.createObjectStore(ENTRY_STORE_NAME,{keyPath:'id'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('IndexedDB open failed.'));});}
function requestToPromise(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('IndexedDB request failed.'));});}
async function withStore(storeName,mode,callback){const db=await openDictionaryDatabase();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(storeName,mode);const store=tx.objectStore(storeName);let result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error||new Error('IndexedDB transaction failed.'));result=callback(store);});}finally{db.close();}}
function chunkId(dictionaryId,chunkIndex){return `${dictionaryId}::chunk::${chunkIndex}`;}
function minimizeEntry(entry){return{term:entry.term||entry.text||'',reading:entry.reading||'',source:entry.source||entry.sourceDictionary||'',sourceDictionary:entry.sourceDictionary||entry.source||'',dictionaryId:entry.dictionaryId||'',dictionaryPriority:Number(entry.dictionaryPriority??entry.priority??9999),dictionaryType:entry.dictionaryType||entry.type||'term',nameType:entry.nameType||'',grammarType:entry.grammarType||'',expressionType:entry.expressionType||'',readings:Array.isArray(entry.readings)?entry.readings:[],tags:Array.isArray(entry.tags)?entry.tags:[],rules:entry.rules||'',score:Number(entry.score||0),sequence:entry.sequence??null,termTags:entry.termTags||''};}
export async function saveActiveDictionarySnapshot({title,entries,summary}){const now=new Date().toISOString();const minimized=(entries||[]).map(minimizeEntry);const snapshot={id:ACTIVE_KEY,title:title||summary?.importedTitle||summary?.index?.title||'Imported dictionary',savedAt:now,entryCount:minimized.length,summary:summary||null,entries:minimized};await withStore(LEGACY_STORE_NAME,'readwrite',store=>store.put(snapshot));return snapshot;}
export async function loadActiveDictionarySnapshot(){return await withStore(LEGACY_STORE_NAME,'readonly',store=>requestToPromise(store.get(ACTIVE_KEY)))||null;}
export async function clearActiveDictionarySnapshot(){await withStore(LEGACY_STORE_NAME,'readwrite',store=>store.delete(ACTIVE_KEY));}
async function deleteEntryChunksForMeta(meta){const n=Number(meta?.chunkCount||0);if(!meta?.id||!n)return;await withStore(ENTRY_STORE_NAME,'readwrite',store=>{for(let i=0;i<n;i+=1)store.delete(chunkId(meta.id,i));});}
export async function saveTermDictionarySnapshot({id,title,priority,entries,summary,profile}){const now=new Date().toISOString();const safeTitle=title||summary?.importedTitle||summary?.index?.title||'Imported dictionary';const safePriority=Number(priority||9999);const entryCount=entries?.length||0;const chunkCount=Math.ceil(entryCount/TERM_ENTRY_CHUNK_SIZE);const existing=await withStore(META_STORE_NAME,'readonly',store=>requestToPromise(store.get(id)));if(existing)await deleteEntryChunksForMeta(existing);const meta={id,title:safeTitle,priority:safePriority,type:profile?.detectedType||summary?.detectionProfile?.detectedType||'term',adapter:profile?.adapter||summary?.detectionProfile?.adapter||'yomitan-term-v3',supported:true,savedAt:now,entryCount,chunkCount,chunkSize:TERM_ENTRY_CHUNK_SIZE,storageMode:'chunked-minimal-detection-v1',profile:profile||summary?.detectionProfile||null,summary:summary?{fileName:summary.fileName||'',importedTitle:summary.importedTitle||safeTitle,importedEntries:summary.importedEntries||entryCount,importedRows:summary.importedRows||entryCount,normalizedEntries:summary.normalizedEntries||entryCount,detectionProfile:summary.detectionProfile||profile||null}:null};await withStore(META_STORE_NAME,'readwrite',store=>store.put(meta));for(let chunkIndex=0;chunkIndex<chunkCount;chunkIndex+=1){const start=chunkIndex*TERM_ENTRY_CHUNK_SIZE;const end=Math.min(start+TERM_ENTRY_CHUNK_SIZE,entryCount);const chunkEntries=[];for(let i=start;i<end;i+=1)chunkEntries.push(minimizeEntry({...entries[i],dictionaryId:id,dictionaryPriority:safePriority,sourceDictionary:safeTitle,source:safeTitle}));await withStore(ENTRY_STORE_NAME,'readwrite',store=>store.put({id:chunkId(id,chunkIndex),dictionaryId:id,chunkIndex,entries:chunkEntries}));}return meta;}
export async function loadTermDictionaryMetas(){const metas=await withStore(META_STORE_NAME,'readonly',store=>requestToPromise(store.getAll()));return(metas||[]).sort((a,b)=>Number(a.priority||9999)-Number(b.priority||9999));}
async function loadEntriesForMeta(meta){if(!meta)return[];if(meta.storageMode==='chunked-minimal-detection-v1'||meta.chunkCount){const entries=[];for(let i=0;i<Number(meta.chunkCount||0);i+=1){const chunk=await withStore(ENTRY_STORE_NAME,'readonly',store=>requestToPromise(store.get(chunkId(meta.id,i))));if(chunk?.entries?.length)entries.push(...chunk.entries);}return entries;}const payload=await withStore(ENTRY_STORE_NAME,'readonly',store=>requestToPromise(store.get(meta.id)));return payload?.entries||[];}
export async function loadTermDictionaryEntriesForMeta(meta){return loadEntriesForMeta(meta);}
export async function loadTermDictionarySnapshots(){const metas=await loadTermDictionaryMetas();const snapshots=[];for(const meta of metas){const entries=await loadEntriesForMeta(meta);snapshots.push({meta,entries});}return snapshots;}
export async function deleteTermDictionarySnapshot(id){const meta=await withStore(META_STORE_NAME,'readonly',store=>requestToPromise(store.get(id)));if(meta)await deleteEntryChunksForMeta(meta);await withStore(META_STORE_NAME,'readwrite',store=>store.delete(id));await withStore(ENTRY_STORE_NAME,'readwrite',store=>store.delete(id));}
export async function clearTermDictionarySnapshots(){await withStore(META_STORE_NAME,'readwrite',store=>store.clear());await withStore(ENTRY_STORE_NAME,'readwrite',store=>store.clear());}
