import registry from '../../docs/ALPHA8_PERSISTENCE_REGISTRY.json' with { type: 'json' };
export const PERSISTENCE_REGISTRY=Object.freeze(registry);
export const PROGRESS_SCHEMA_VERSION=2;
const BACKUP_PREFIX='novel-audio-miner:persistence-backup:';
const RECEIPT_PREFIX='novel-audio-miner:persistence-receipt:';
function object(v){return v!==null&&typeof v==='object'&&!Array.isArray(v);}
function stamp(now=new Date()){return now.toISOString();}
export function classifyJsonRecord(raw,{currentVersion,legacyVersions=[]}={}){if(raw==null)return Object.freeze({state:'absent',value:null,version:null,errors:[]});let value;try{value=JSON.parse(raw);}catch{return Object.freeze({state:'corrupt',value:null,version:null,errors:['invalid-json']});}if(!object(value))return Object.freeze({state:'corrupt',value:null,version:null,errors:['record-not-object']});const version=Number(value.version??0);if(version===Number(currentVersion))return Object.freeze({state:'current',value,version,errors:[]});if(legacyVersions.map(Number).includes(version))return Object.freeze({state:'migratable',value,version,errors:[]});return Object.freeze({state:'incompatible',value,version,errors:['unsupported-version']});}
export function validateProgressPayload(value){const errors=[];if(!object(value))errors.push('progress-not-object');const state=object(value?.state)?value.state:value;if(state?.itemIndex!=null&&(!Number.isInteger(state.itemIndex)||state.itemIndex<0))errors.push('invalid-item-index');if(state?.readerStyle!=null&&!object(state.readerStyle))errors.push('invalid-reader-style');return Object.freeze({valid:errors.length===0,errors:Object.freeze(errors),state});}
export function migrateProgressRecord(raw,now=new Date()){const classified=classifyJsonRecord(raw,{currentVersion:PROGRESS_SCHEMA_VERSION,legacyVersions:[0,1]});if(classified.state==='current'){const check=validateProgressPayload(classified.value);return Object.freeze({state:check.valid?'current':'corrupt',record:check.valid?classified.value:null,errors:check.errors});}if(classified.state!=='migratable')return Object.freeze({...classified,record:null});const check=validateProgressPayload(classified.value);if(!check.valid)return Object.freeze({state:'corrupt',record:null,errors:check.errors});return Object.freeze({state:'migratable',record:{version:PROGRESS_SCHEMA_VERSION,savedAt:stamp(now),state:{...check.state}},errors:[]});}
export function safeMigrateLocalStorage({storage,key,migrate,now=new Date()}){const raw=storage.getItem(key);const plan=migrate(raw,now);if(plan.state==='absent'||plan.state==='current')return Object.freeze({...plan,mutated:false});if(plan.state!=='migratable'||!plan.record)return Object.freeze({...plan,mutated:false});const backupKey=`${BACKUP_PREFIX}${encodeURIComponent(key)}:${now.getTime()}`;const receiptKey=`${RECEIPT_PREFIX}${encodeURIComponent(key)}`;storage.setItem(backupKey,raw);try{storage.setItem(key,JSON.stringify(plan.record));const verify=migrate(storage.getItem(key),now);if(verify.state!=='current')throw new Error('migrated-readback-invalid');const receipt={schemaVersion:'1.0',key,backupKey,fromVersion:plan.version??0,toVersion:plan.record.version,migratedAt:stamp(now),rollbackAvailable:true};storage.setItem(receiptKey,JSON.stringify(receipt));return Object.freeze({state:'current',record:plan.record,receipt:Object.freeze(receipt),mutated:true});}catch(error){storage.setItem(key,raw);return Object.freeze({state:'recovery-required',record:null,backupKey,error:error?.message||String(error),mutated:false});}}
export function readProgressRecord(storage,key,now=new Date()){const plan=migrateProgressRecord(storage.getItem(key),now);if(plan.state==='current')return plan.record.state;if(plan.state==='migratable'){const result=safeMigrateLocalStorage({storage,key,migrate:migrateProgressRecord,now});return result.state==='current'?result.record.state:null;}return null;}
export function writeProgressRecord(storage,key,state,now=new Date()){const check=validateProgressPayload(state);if(!check.valid)throw new Error(`Invalid Reader progress: ${check.errors.join(', ')}`);const record={version:PROGRESS_SCHEMA_VERSION,savedAt:stamp(now),state:{...state}};storage.setItem(key,JSON.stringify(record));const verify=migrateProgressRecord(storage.getItem(key),now);if(verify.state!=='current')throw new Error('Reader progress read-back validation failed.');return Object.freeze(record);}
export function inspectPersistenceHealth(storage){const results=[];for(const item of registry.records){if(item.medium!=='localStorage'){results.push({id:item.id,state:'read-only',medium:item.medium,owner:item.owner});continue;}if(item.keyPattern.includes('<bookId>')){results.push({id:item.id,state:'healthy',medium:item.medium,owner:item.owner,note:'book-scoped keys validated on access'});continue;}const raw=storage?.getItem?.(item.keyPattern)??null;results.push({id:item.id,...classifyJsonRecord(raw,{currentVersion:item.currentVersion,legacyVersions:item.legacyVersions}),medium:item.medium,owner:item.owner});}return Object.freeze({schemaVersion:registry.schema,registryVersion:registry.version,checkedAt:stamp(),records:Object.freeze(results.map(x=>Object.freeze(x))),mutationPerformed:false});}
