function compare(a,b){return a.spineIndex-b.spineIndex||a.eventIndex-b.eventIndex;}
function contains(section,occurrence){if(!section?.start||!section?.end)return false;return compare(occurrence,section.start)>=0&&compare(occurrence,section.end)<=0;}
function sectionFor(bookModel,occurrence){const matches=(bookModel?.sections||[]).filter(section=>contains(section,occurrence));return matches.find(section=>section.type==='navigation')||matches.find(section=>section.type==='cover')||matches.find(section=>section.type==='chapter')||matches[0]||null;}
function ratio(value,total){return total?value/total:0;}
function confidence(role,occurrence){
 if(role==='cover'||role==='navigation-image'||role==='front-matter-illustration')return'high';
 if(role==='inline-illustration')return occurrence.hasTextBefore&&occurrence.hasTextAfter?'high':'medium';
 if(role==='ornament'||role==='publisher-mark'||role==='chapter-title-artwork'||role==='chapter-opening-illustration'||role==='full-page-illustration')return'medium';
 return'low';
}
function classify(occurrence,resource){const evidence=[],counterEvidence=[];let candidateRole='unknown';
 const strongOrnament=resource.occurrenceCount>=3&&resource.documentCount>=3&&resource.chapterCount>=2&&resource.betweenTextRatio>=0.66&&resource.chapterStartCount===0&&resource.frontMatterCount===0&&resource.navigationCount===0;
 const repeatedPublisherMark=resource.occurrenceCount>=3&&resource.documentCount>=3&&resource.documentEndRatio>=0.66&&resource.betweenTextRatio<0.5&&resource.chapterStartCount===0&&resource.frontMatterCount===0&&resource.navigationCount===0&&(resource.backMatterCount>0||resource.chapterCount>=2);
 const isolatedAuxiliaryMark=resource.occurrenceCount===1&&occurrence.eventPositionInDocument==='last-event'&&occurrence.documentImageCount===1&&occurrence.documentTextEventCount<=2&&!occurrence.hasTextAfter&&!occurrence.isChapterStart&&['front-matter','back-matter','auxiliary'].includes(occurrence.sectionType);
 const publisherMark=repeatedPublisherMark||isolatedAuxiliaryMark;
 if(occurrence.isChosenCover){candidateRole='cover';evidence.push('chosen-cover-occurrence','declared-or-guide-cover');}
 else if(occurrence.sectionType==='navigation'){candidateRole='navigation-image';evidence.push('non-readable-navigation-section');}
 else if(strongOrnament){candidateRole='ornament';evidence.push('resource-repeated-across-documents','resource-repeated-across-chapters','usually-between-text-events','not-at-chapter-start');counterEvidence.push('image-dimensions-unavailable');}
 else if(publisherMark){candidateRole='publisher-mark';if(repeatedPublisherMark)evidence.push('resource-repeated-across-documents','usually-at-document-end');if(isolatedAuxiliaryMark)evidence.push('isolated-terminal-image','minimal-document-text','auxiliary-section');evidence.push('not-at-chapter-start');if(resource.backMatterCount>0)evidence.push('back-matter-occurrence');counterEvidence.push('image-dimensions-unavailable');}
 else if(occurrence.isChapterStart&&occurrence.documentImageCount===1&&occurrence.documentTextEventCount===0){candidateRole='chapter-title-artwork';evidence.push('chapter-start','image-only-document','single-image-document');counterEvidence.push('may-be-chapter-opening-illustration');}
 else if(occurrence.isChapterStart){candidateRole='chapter-opening-illustration';evidence.push('chapter-start','prose-or-additional-events-follow');}
 else if(occurrence.documentTextEventCount===0&&occurrence.documentImageCount===1){candidateRole=occurrence.sectionType==='front-matter'?'front-matter-illustration':'full-page-illustration';evidence.push('image-only-document','single-image-document');if(occurrence.sectionType==='front-matter')evidence.push('front-matter-section');}
 else if(occurrence.hasTextBefore||occurrence.hasTextAfter){candidateRole='inline-illustration';evidence.push('shares-document-with-text');if(occurrence.hasTextBefore)evidence.push('text-before-image');if(occurrence.hasTextAfter)evidence.push('text-after-image');}
 if(resource.occurrenceCount>=3&&candidateRole!=='cover'&&candidateRole!=='navigation-image'&&!evidence.includes('resource-repeated-across-documents'))evidence.push('resource-repeated');
 return{candidateRole,confidence:confidence(candidateRole,occurrence),evidence,counterEvidence};}
export function buildEpubImageRoleModel({packageModel,documents=[],bookModel}={}){const raw=[];for(const document of documents){const events=document.events||[],images=events.filter(e=>e.type==='image'),text=events.filter(e=>e.type==='text-block'||e.type==='heading');for(const event of images){const section=sectionFor(bookModel,{spineIndex:document.spineIndex,eventIndex:event.eventIndex});raw.push({resourceHref:event.imageHref,documentHref:document.documentHref,spineIndex:document.spineIndex,eventIndex:event.eventIndex,sectionIndex:section?.sectionIndex??null,sectionType:section?.type||'unclassified',chapterNavigationIndex:section?.type==='chapter'?section.navigationIndex??null:null,documentImageCount:images.length,documentTextEventCount:text.length,eventPositionInDocument:events.length===1?'only-event':event.eventIndex===0?'first-event':event.eventIndex===events.length-1?'last-event':'middle-event',hasTextBefore:text.some(x=>x.eventIndex<event.eventIndex),hasTextAfter:text.some(x=>x.eventIndex>event.eventIndex),isChapterStart:section?.type==='chapter'&&compare({spineIndex:document.spineIndex,eventIndex:event.eventIndex},section.start)===0,isChosenCover:Boolean(bookModel?.cover?.chosen&&bookModel.cover.chosen.documentHref===document.documentHref&&bookModel.cover.chosen.eventIndex===event.eventIndex),altTextPresent:Boolean(event.alt),altTextLength:String(event.alt||'').length});}}
 raw.sort(compare);const groups=new Map();for(const item of raw){if(!groups.has(item.resourceHref))groups.set(item.resourceHref,[]);groups.get(item.resourceHref).push(item);}const resources=[];for(const[resourceHref,items]of groups){const occurrenceCount=items.length,betweenTextCount=items.filter(x=>x.hasTextBefore&&x.hasTextAfter).length,documentEndCount=items.filter(x=>x.eventPositionInDocument==='last-event'||x.eventPositionInDocument==='only-event').length;resources.push({resourceHref,occurrenceCount,documentCount:new Set(items.map(x=>x.documentHref)).size,sectionCount:new Set(items.map(x=>x.sectionIndex).filter(x=>x!=null)).size,chapterCount:new Set(items.map(x=>x.chapterNavigationIndex).filter(x=>x!=null)).size,documentStartCount:items.filter(x=>x.eventPositionInDocument==='first-event'||x.eventPositionInDocument==='only-event').length,documentEndCount,betweenTextCount,betweenTextRatio:ratio(betweenTextCount,occurrenceCount),documentEndRatio:ratio(documentEndCount,occurrenceCount),chapterStartCount:items.filter(x=>x.isChapterStart).length,frontMatterCount:items.filter(x=>x.sectionType==='front-matter').length,navigationCount:items.filter(x=>x.sectionType==='navigation').length,backMatterCount:items.filter(x=>x.sectionType==='back-matter'||x.sectionType==='auxiliary').length});}
 const byResource=new Map(resources.map(x=>[x.resourceHref,x]));const occurrences=raw.map((item,index)=>{const resource=byResource.get(item.resourceHref);return Object.freeze({occurrenceIndex:index,...item,resourceOccurrenceCount:resource.occurrenceCount,resourceDocumentCount:resource.documentCount,resourceChapterCount:resource.chapterCount,resourceBetweenTextRatio:resource.betweenTextRatio,...classify(item,resource)});});for(const resource of resources){const roles=occurrences.filter(x=>x.resourceHref===resource.resourceHref);const counts={};for(const item of roles)counts[item.candidateRole]=(counts[item.candidateRole]||0)+1;const candidateRole=Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]||'unknown';resource.candidateRole=candidateRole;resource.confidence=roles.every(x=>x.candidateRole===candidateRole)?roles[0].confidence:'low';}
 const roleCounts={};for(const item of occurrences)roleCounts[item.candidateRole]=(roleCounts[item.candidateRole]||0)+1;return Object.freeze({schemaVersion:'13.5A',occurrenceCount:occurrences.length,resourceCount:resources.length,roleCounts:Object.freeze(roleCounts),occurrences:Object.freeze(occurrences),resources:Object.freeze(resources),lowConfidenceCandidates:Object.freeze(occurrences.filter(x=>x.confidence==='low').map(x=>x.occurrenceIndex)),diagnostics:Object.freeze({coverCount:roleCounts.cover||0,navigationImageCount:roleCounts['navigation-image']||0,chapterOpeningCandidateCount:(roleCounts['chapter-title-artwork']||0)+(roleCounts['chapter-opening-illustration']||0),ornamentCount:roleCounts.ornament||0,publisherMarkCount:roleCounts['publisher-mark']||0,unknownCount:roleCounts.unknown||0,repeatedResourceCount:resources.filter(x=>x.occurrenceCount>1).length})});}
export function sanitizeEpubImageRoleModel(model){return model?JSON.parse(JSON.stringify(model)):null;}
