import {useState} from 'react';
import {generateTeachingCorpusDryRun,previewTeachingCorpusExport,verifyTeachingCorpusArtifact} from '../lib/teachingCorpusExportClient.js';
function downloadJson(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
export default function TeachingCorpusExportPanel(){
 const [preview,setPreview]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{const value=await previewTeachingCorpusExport();setPreview(value);setMessage('Dry-run preview generated. No training or activation occurred.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function validate(){if(!preview){setMessage('Generate a preview first.');return;}setBusy(true);try{const result=await verifyTeachingCorpusArtifact(preview);setMessage(result.ok?'Corpus manifest is valid. Export and activation remain disabled.':`Validation failed: ${result.problems.join(', ')}`);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function generate(){setBusy(true);try{const result=await generateTeachingCorpusDryRun();setPreview(result.artifact);downloadJson(`teaching-corpus-${result.artifact.corpusDigest.slice(7,19)}.json`,result);setMessage(result.notice);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <details className="teaching-corpus-export"><summary>Corpus export dry run</summary><p>Creates a deterministic JSON package for inspection only. This does not train, tune, or activate the analyzer.</p><div className="teaching-actions"><button type="button" disabled={busy} onClick={load}>Preview export</button><button type="button" disabled={busy||!preview} onClick={validate}>Validate corpus</button><button type="button" disabled={busy} onClick={generate}>Generate dry-run package</button></div>{preview&&<><div className="teaching-preview-meta"><span>Eligible: {preview.eligibleCount}</span><span>Excluded: {preview.excludedCount}</span><span>Train: {preview.splitCounts?.train||0}</span><span>Validation: {preview.splitCounts?.validation||0}</span><span>Test: {preview.splitCounts?.test||0}</span><span>Export: disabled</span></div><code>{preview.corpusDigest}</code>{preview.excludedRecords?.length>0&&<details><summary>Exclusion reasons</summary>{preview.excludedRecords.map(x=><div key={x.recordId}><code>{x.recordId}</code><span>{x.reasons.join(', ')}</span></div>)}</details>}</>}{message&&<div className="status-message">{message}</div>}</details>;
}
