import {useState} from 'react';
import {previewControlledActivation,createShadowPlan,verifyShadowPlan} from '../lib/teachingControlledActivationClient.js';
function downloadJson(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
export default function TeachingControlledActivationPanel(){
 const [preview,setPreview]=useState(null),[plan,setPlan]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{const value=await previewControlledActivation();setPreview(value);setPlan(value.plan||null);setMessage(value.eligible?'Shadow activation is eligible. Live activation remains disabled.':`Not eligible: ${value.reason}`);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function create(){setBusy(true);try{const value=await createShadowPlan(preview?.experiment);setPlan(value.plan);downloadJson(`shadow-plan-${value.plan.planId}.json`,value);setMessage(value.notice);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function verify(){if(!plan){setMessage('Create a shadow plan first.');return;}setBusy(true);try{const value=await verifyShadowPlan(plan);setMessage(value.ok?'Shadow plan is valid. Live mutation remains disabled.':`Plan invalid: ${value.problems.join(', ')}`);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <details className="teaching-controlled-activation"><summary>Controlled activation</summary><p>Shadow observation only. This does not replace Reader output, change the dictionary, or deploy analyzer behavior.</p><div className="teaching-actions"><button type="button" disabled={busy} onClick={load}>Check eligibility</button><button type="button" disabled={busy||!preview?.eligible} onClick={create}>Create shadow plan</button><button type="button" disabled={busy||!plan} onClick={verify}>Verify rollback plan</button></div>{plan&&<><div className="teaching-preview-meta"><span>Mode: shadow</span><span>Live mutation: disabled</span><span>Automatic deployment: disabled</span><span>Rollback: required</span></div><code>{plan.planDigest}</code></>}{message&&<div className="status-message">{message}</div>}</details>;
}
