import { useEffect, useMemo, useState } from 'react';
import { captureTeachingSnapshot, createTeachingDecision, listTeachingDecisions, retractTeachingDecision, supersedeTeachingDecision, teachingDecisionDiagnosis, teachingDecisionSummary } from '../lib/teachingDecisionClient.js';
const JUDGMENTS=[['accepted-current','✓ Analyzer is correct'],['corrected','Record correction'],['rejected','Reject analyzer decision']];
const ROLES=['','lexical','learnable-grammar','function','name','unresolved'];
const FAILURES=['unclassified','candidate-generation-miss','ranking-error','hard-gate-error','boundary-error','role-error','identity-error','partition-optimization-error','abstention-error'];
async function sha256(value){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export default function TeachingDecisionPanel({selection,analysis,provenance}){
 const [judgment,setJudgment]=useState('accepted-current'),[assertedRole,setAssertedRole]=useState(''),[identityKey,setIdentityKey]=useState(''),[failure,setFailure]=useState('unclassified'),[confidence,setConfidence]=useState('preference'),[note,setNote]=useState('');
 const [records,setRecords]=useState([]),[summary,setSummary]=useState(null),[diagnosis,setDiagnosis]=useState(null),[selectedRecord,setSelectedRecord]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [filters,setFilters]=useState({judgment:'',lifecycle:'',failure:''});
 const observed=useMemo(()=>(analysis?.words||[]).find(x=>x.start===selection?.start&&x.end===selection?.end)||null,[analysis,selection]);
 const canAcceptCurrent=Boolean(observed);
 async function refresh(){if(!selection?.sentence)return;try{const sentenceSha256=await sha256(selection.sentence);const [items,totals]=await Promise.all([listTeachingDecisions({sentenceSha256,lifecycleStatus:null}),teachingDecisionSummary()]);setRecords(items.records||[]);setSummary(totals);}catch(e){setMessage(e.message);}}
 useEffect(()=>{setJudgment(canAcceptCurrent?'accepted-current':'corrected');setAssertedRole('');setIdentityKey('');setFailure('unclassified');setNote('');setMessage('');setDiagnosis(null);setSelectedRecord(null);refresh();},[selection?.sentence,selection?.start,selection?.end,canAcceptCurrent]);
 const visible=records.filter(r=>(!filters.judgment||r.judgment===filters.judgment)&&(!filters.lifecycle||r.lifecycle?.status===filters.lifecycle)&&(!filters.failure||r.failureClassification===filters.failure));
 async function payload(){const snapshot=await captureTeachingSnapshot(selection.sentence);const role=judgment==='accepted-current'?(observed?.displayRole||observed?.role||'unresolved'):(assertedRole||'unresolved');return {snapshot,boundary:{start:selection.start,end:selection.end,surface:selection.surface},judgment,classification:{assertedRole:role},identity:identityKey.trim()?{assertedLookupKey:identityKey.trim()}:null,approvedTarget:judgment==='corrected'?{targetSpans:[{start:selection.start,end:selection.end,surface:selection.surface,displayRole:role}],provenance:provenance||null}:null,failureClassification:judgment==='accepted-current'?'accepted-current':failure,confidence,note:note.trim()||null,operationalCorrectionLink:null};}
 async function save(replaceId=null){if(judgment==='accepted-current'&&!canAcceptCurrent){setMessage('Select one complete analyzer span before accepting it.');return;}setBusy(true);setMessage('Capturing authoritative snapshot...');try{const body=await payload();const result=replaceId?await supersedeTeachingDecision(replaceId,body):await createTeachingDecision(body);setMessage(replaceId?`Decision superseded by ${result.replacement.recordId}`:`Decision saved: ${result.recordId}`);setSelectedRecord(null);await refresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function inspect(record){setSelectedRecord(record);setDiagnosis(null);try{setDiagnosis(await teachingDecisionDiagnosis(record.recordId));}catch(e){setMessage(e.message);}}
 async function retract(id){if(!window.confirm(`Retract ${id}? History is retained.`))return;setBusy(true);try{await retractTeachingDecision(id,'Retracted in Alpha 6 review management');await refresh();setMessage('Decision retracted; history retained.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <section className="teaching-decision-panel" data-testid="teaching-decision-panel">
  <strong>Review analyzer decision</strong><span>Test-only evidence. Export and analyzer activation remain disabled.</span>
  {summary&&<div className="teaching-preview-meta"><span>Corpus: {summary.recordCount}</span><span>Integrity: {summary.integrity?.ok?'ok':'issues'}</span><span>Export: disabled ? exportStatus: excluded</span></div>}
  <div className="teaching-actions">{JUDGMENTS.map(([value,label])=><button type="button" key={value} className={judgment===value?'teaching-action active':'teaching-action'} disabled={value==='accepted-current'&&!canAcceptCurrent} title={value==='accepted-current'&&!canAcceptCurrent?'Select one complete analyzer span':undefined} onClick={()=>setJudgment(value)}>{label}</button>)}</div>
  {!canAcceptCurrent&&<div className="status-message">Partial selection: select a complete analyzer span to accept the current decision.</div>}
  {judgment!=='accepted-current'&&<><label>Classification<select value={assertedRole} onChange={e=>setAssertedRole(e.target.value)}>{ROLES.map(x=><option key={x} value={x}>{x||'Choose classification'}</option>)}</select></label><label>Failure<select value={failure} onChange={e=>setFailure(e.target.value)}>{FAILURES.map(x=><option key={x}>{x}</option>)}</select></label><label>Identity<input value={identityKey} onChange={e=>setIdentityKey(e.target.value)} /></label></>}
  <label>Confidence<select value={confidence} onChange={e=>setConfidence(e.target.value)}><option value="preference">Preference</option><option value="confident">Confident</option><option value="needs-review">Needs review</option></select></label><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} /></label>
  <button type="button" disabled={busy||(judgment==='accepted-current'&&!canAcceptCurrent)||(judgment!=='accepted-current'&&!assertedRole)} onClick={()=>save()}>Save review decision</button>
  {message&&<div className="status-message">{message}</div>}
  <details><summary>Decision history and management</summary><div className="teaching-actions"><select value={filters.judgment} onChange={e=>setFilters({...filters,judgment:e.target.value})}><option value="">All judgments</option>{JUDGMENTS.map(x=><option key={x[0]} value={x[0]}>{x[0]}</option>)}</select><select value={filters.lifecycle} onChange={e=>setFilters({...filters,lifecycle:e.target.value})}><option value="">All lifecycle states</option><option>active</option><option>retracted</option><option>superseded</option></select><select value={filters.failure} onChange={e=>setFilters({...filters,failure:e.target.value})}><option value="">All failures</option>{FAILURES.map(x=><option key={x}>{x}</option>)}</select></div>
   <div className="teaching-existing">{visible.map(r=><div key={r.recordId}><button type="button" className="secondary" onClick={()=>inspect(r)}>Inspect</button><span>{r.judgment} · {r.lifecycle?.status} · {r.failureClassification}</span><code>{r.recordId}</code>{r.lifecycle?.status==='active'&&<><button type="button" onClick={()=>save(r.recordId)} disabled={busy}>Supersede with current review</button><button type="button" className="danger-button" onClick={()=>retract(r.recordId)} disabled={busy}>Retract</button></>}</div>)}</div>
  </details>
  {selectedRecord&&<div className="teaching-preview"><strong>Decision comparison</strong><div><span>Observed</span><code>{JSON.stringify(selectedRecord.decisionComparison?.observedReaderSpan||null)}</code></div><div><span>Approved</span><code>{JSON.stringify(selectedRecord.approvedTarget||null)}</code></div>{diagnosis&&<div className="teaching-preview-meta"><span>Candidate: {diagnosis.candidatePresent?'present':'missing'}</span><span>Boundary: {diagnosis.boundaryMatches?'match':'different'}</span><span>Classification: {diagnosis.classificationMatches?'match':'different'}</span><span>Correction linked: {diagnosis.operationalCorrectionLinked?'yes':'no'}</span></div>}</div>}
 </section>;
}
