import {useState} from 'react';
import {previewOfflineEvaluation,runOfflineEvaluation,verifyOfflineExperiment} from '../lib/teachingOfflineEvaluationClient.js';
function downloadJson(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
function metric(value){return value==null?'n/a':`${(value*100).toFixed(1)}%`;}
export default function TeachingOfflineEvaluationPanel(){
 const [result,setResult]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function preview(){setBusy(true);try{const value=await previewOfflineEvaluation();setResult(value);setMessage('Offline preview generated. The live analyzer was not changed.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function run(){setBusy(true);try{const value=await runOfflineEvaluation();setResult(value.experiment);setMessage(value.notice);downloadJson(`offline-experiment-${value.experiment.experimentId}.json`,value);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function verify(){if(!result){setMessage('Generate an offline preview first.');return;}setBusy(true);try{const value=await verifyOfflineExperiment(result);setMessage(value.ok?'Experiment artifact is valid. Deployment remains disabled.':`Validation failed: ${value.problems.join(', ')}`);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const validation=result?.after?.validation?.metrics||{};
 return <details className="teaching-offline-evaluation"><summary>Offline evaluation experiment</summary><p>Running an offline experiment does not change the live analyzer. Dictionary mutation and deployment remain disabled.</p><div className="teaching-actions"><button type="button" disabled={busy} onClick={preview}>Preview baseline</button><button type="button" disabled={busy} onClick={run}>Run offline evaluation</button><button type="button" disabled={busy||!result} onClick={verify}>Verify report</button></div>{result&&<><div className="teaching-preview-meta"><span>Result: {result.passed?'pass':'review'}</span><span>Train: {result.before?.train?.recordCount||0}</span><span>Validation: {result.before?.validation?.recordCount||0}</span><span>Test: {result.before?.test?.recordCount||0}</span><span>Deployment: disabled</span></div><div className="teaching-preview-meta"><span>Candidate recall: {metric(validation.candidateGenerationRecall)}</span><span>Boundary: {metric(validation.boundaryAccuracy)}</span><span>Classification: {metric(validation.classificationAccuracy)}</span><span>Identity: {metric(validation.identityAccuracy)}</span></div><code>{result.artifactDigest}</code>{result.regressions?.length>0&&<details><summary>Regressions</summary>{result.regressions.map((x,i)=><div key={`${x.metric}-${i}`}>{x.split}: {x.metric} {x.delta}</div>)}</details>}</>}{message&&<div className="status-message">{message}</div>}</details>;
}
